### ISSUE TITLE
Error messages appearing in Transcript

### ISSUE THREAD

**Issue by MrModder** [hpi-swa-lab/CommunityCodeReview#25]
After installing CommunityCodeReview via Metacello and opening a CCBrowser, about every 10s an error message appears in the Transcript:
```Error in CC synchronization process: CCRemoteCodeError: CCCommentDictionary class>>addLike: is not a valid selector```

**Comment by codeZeilen** [comment]
There is an erroneous state on the server maybe due to tests not being completely isolated.

**Comment by tobiasduerschmid** [comment]
Seem to be fixed now by removing some bad legacy state.
